apiVersion: v1
kind: Service
metadata:
  name: boardsync-service
  namespace: boardsync-ns
spec:
  type: NodePort
  selector:
    app: boardsync
  ports:
  - port: 80
    targetPort: 5173
    nodePort: 30007
  - port: 3000
    targetPort: 3000